name       : e2fsprogs
version    : 1.46.5
release    : 21
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.46.5/e2fsprogs-1.46.5.tar.xz : 2f16c9176704cf645dc69d5b15ff704ae722d665df38b2ed3cfc249757d8d81e
homepage   : http://e2fsprogs.sourceforge.net
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - BSD
    - MIT
component  : system.base
autodep    : no
emul32     : yes
summary    : e2fsprogs (Filesystem utilities for ext2/3/4 filesystems)
description: |
    e2fsprofs are tools for checking and creating ext2, ext3, and ext4 filesystem formats.  They were written by Theodore Ts'o and Remy Card.
builddeps  :
    - pkgconfig32(uuid)
    - glibc-32bit-devel
    - libgcc-32bit
patterns   :
    - devel : [ /usr/share/man/man3* ]
setup      : |
    %configure --with-root-prefix="" \
        --enable-elf-shlibs \
        --disable-libblkid \
        --disable-libuuid \
        --disable-static \
        --disable-uuidd
build      : |
    %make
install    : |
    %make_install
    %make install-libs DESTDIR="$installdir"
    rm $installdir/sbin/fsck
check      : |
    # Remove mmp since it fails on build server
    rm -rf tests/*mmp*
    %make check -k 0 || :
