name       : e2fsprogs
version    : 1.43.7
release    : 12
source     :
    - https://www.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.43.7/e2fsprogs-1.43.7.tar.xz : 2a6367289047d68d9ba6a46cf89ab9a1efd0556cde02a51ebaf414ff51edded9
homepage   : http://e2fsprogs.sourceforge.net
license    :
    - GPL-2.0
    - LGPL-2.0
    - BSD
    - MIT
component  : system.base
autodep    : no
emul32     : yes
summary    : e2fsprogs (Filesystem utilities for ext2/3/4 filesystems)
description: |
    e2fsprofs are tools for checking and creating ext2, ext3, and ext4 filesystem formats.  They were written by Theodore Ts'o and Remy Card.
builddeps  :
    - pkgconfig32(uuid)
    - glibc-32bit-devel
    - libgcc-32bit
patterns   :
    - devel : [/usr/share/man/man3*]
setup      : |
    %configure --with-root-prefix="" \
        --enable-elf-shlibs \
        --disable-libblkid \
        --disable-libuuid \
        --disable-static \
        --disable-uuidd
build      : |
    %make
install    : |
    %make_install
    %make install-libs DESTDIR="$installdir"
    rm $installdir/sbin/fsck
