name       : e2fsprogs
version    : 1.45.6
release    : 20
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.45.6/e2fsprogs-1.45.6.tar.xz : ffa7ae6954395abdc50d0f8605d8be84736465afc53b8938ef473fcf7ff44256
homepage   : http://e2fsprogs.sourceforge.net
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - BSD
    - MIT
component  : system.base
autodep    : no
emul32     : yes
summary    : e2fsprogs (Filesystem utilities for ext2/3/4 filesystems)
description: |
    e2fsprofs are tools for checking and creating ext2, ext3, and ext4 filesystem formats.  They were written by Theodore Ts'o and Remy Card.
builddeps  :
    - pkgconfig32(uuid)
    - glibc-32bit-devel
    - libgcc-32bit
patterns   :
    - devel : [/usr/share/man/man3*]
setup      : |
    %configure --with-root-prefix="" \
        --enable-elf-shlibs \
        --disable-libblkid \
        --disable-libuuid \
        --disable-static \
        --disable-uuidd
build      : |
    %make
install    : |
    %make_install
    %make install-libs DESTDIR="$installdir"
    rm $installdir/sbin/fsck
check      : |
    # Remove mmp since it fails on build server
    rm -rf tests/*mmp*
    %make check
